In [1]:
import numpy as np

In [2]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20], 
              [21, 22, 23, 24, 25], 
              [26, 27, 28, 29, 30], 
              [31, 32, 33, 34, 35]])

In [3]:
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [4]:
y = np.apply_along_axis(np.sum, 0, x)

In [5]:
print(y) #[105 110 115 120 125]

[105 110 115 120 125]


In [6]:
y = np.apply_along_axis(np.sum, 1, x)

In [7]:
print(y)

[ 65  90 115 140 165]


In [8]:
y = np.apply_along_axis(np.mean, 0, x)

In [9]:
print(y)

[21. 22. 23. 24. 25.]


In [10]:
y = np.apply_along_axis(np.mean, 1, x)

In [11]:
print(y)

[13. 18. 23. 28. 33.]


In [12]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
print(x.shape)

(8,)


In [14]:
x.shape = [2, 4]

In [15]:
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [30]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20], 
              [21, 22, 23, 24, 25], 
              [26, 27, 28, 29, 30], 
              [31, 32, 33, 34, 35]])

In [31]:
y = x.flat

In [32]:
print(y)

In [33]:
for i in y:
    print(i, end=' ')

11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 

In [34]:
y[3] = 0

In [35]:
print(end='\n')

In [36]:
print(x)

[[11 12 13  0 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [37]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20], 
              [21, 22, 23, 24, 25], 
              [26, 27, 28, 29, 30], 
              [31, 32, 33, 34, 35]])

In [38]:
y = x.flatten()

In [39]:
print(y) #[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]


In [40]:
y[3] = 0

In [41]:
print(y)

[11 12 13  0 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]


In [43]:
print(x)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [44]:
y = x.flatten(order='F')

In [45]:
print(y)

[11 16 21 26 31 12 17 22 27 32 13 18 23 28 33 14 19 24 29 34 15 20 25 30
 35]


In [46]:
y[3] = 0

In [47]:
print(x)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [48]:
print(y)

[11 16 21  0 31 12 17 22 27 32 13 18 23 28 33 14 19 24 29 34 15 20 25 30
 35]


In [49]:
y = x.flatten('C')

In [50]:
print(y)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]


In [51]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20], 
              [21, 22, 23, 24, 25], 
              [26, 27, 28, 29, 30], 
              [31, 32, 33, 34, 35]])

In [52]:
y = np.ravel(x)

In [53]:
print(y)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]


In [55]:
print(x)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [56]:
y[3] = 0

In [57]:
print(y)

[11 12 13  0 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]


In [58]:
x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20], 
              [21, 22, 23, 24, 25], 
              [26, 27, 28, 29, 30], 
              [31, 32, 33, 34, 35]])

In [59]:
y = np.ravel(x, order='F')

In [60]:
print(y)

[11 16 21 26 31 12 17 22 27 32 13 18 23 28 33 14 19 24 29 34 15 20 25 30
 35]


In [61]:
y[3] = 0

In [62]:
print(y)

[11 16 21  0 31 12 17 22 27 32 13 18 23 28 33 14 19 24 29 34 15 20 25 30
 35]


In [63]:
print(x)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [65]:
x = np.arange(12)

In [66]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [67]:
y = np.reshape(x, [3, 4])

In [68]:
print(y.dtype)

int64


In [69]:
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [70]:
y = np.reshape(x, [6, -1])

In [71]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [72]:
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [73]:
y = np.reshape(x, [3, -1])

In [74]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [75]:
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [76]:
print(np.reshape(x, [-1, 3]))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [77]:
y[0, 1] = 10

In [78]:
print(y)

[[ 0 10  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [79]:
print(x)

[ 0 10  2  3  4  5  6  7  8  9 10 11]


In [80]:
x = np.random.randint(12, size=[2, 2, 3])

In [81]:
print(x)

[[[7 8 9]
  [5 2 4]]

 [[5 5 5]
  [2 4 3]]]


In [82]:
y = np.reshape(x, -1)

In [83]:
print(y)

[7 8 9 5 2 4 5 5 5 2 4 3]
