In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3, 4])
b = np.array((0, 1, 2, 3, 4))


In [3]:
print(a, type(a))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [4]:
print(b, type(b))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [6]:
c = np.array([[11, 12, 13, 14, 15],
               [16, 17, 18, 19 ,20],
               [21, 22, 23, 24, 25],
               [26, 27, 28, 29, 30],
               [31, 32, 33, 34, 35]])

In [7]:
print(c, type(c))

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]] <class 'numpy.ndarray'>


In [8]:
d = np.array([[(1, 2, 3), (4, 5, 6)]])

In [9]:
print(d)

[[[1 2 3]
  [4 5 6]]]


In [10]:
x = [[1, 1, 1],
     [1, 1, 1],
     [1, 1, 1]]

In [11]:
print(x, type(x))

[[1, 1, 1], [1, 1, 1], [1, 1, 1]] <class 'list'>


In [12]:
y = np.array(x)

In [13]:
z = np.asarray(x)

In [14]:
x[1][2] = 2

In [15]:
print(x, type(x))

[[1, 1, 1], [1, 1, 2], [1, 1, 1]] <class 'list'>


In [16]:
print(y, type(y))

[[1 1 1]
 [1 1 1]
 [1 1 1]] <class 'numpy.ndarray'>


In [17]:
print(z, type(z))

[[1 1 1]
 [1 1 1]
 [1 1 1]] <class 'numpy.ndarray'>


In [19]:
w = np.asarray(x, dtype=np.int)

In [20]:
print(w, type(w), w.dtype)

[[1 1 1]
 [1 1 2]
 [1 1 1]] <class 'numpy.ndarray'> int64


In [21]:
x.dtype = np.float

AttributeError: 'list' object has no attribute 'dtype'

In [22]:
def f(x, y):
    return 10 * x + y

In [23]:
x = np.fromfunction(f, (5, 4), dtype=int)

In [24]:
print(x)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [25]:
x = np.fromfunction(lambda i, j:i == j, (3, 3), dtype=int)

In [27]:
print(x)

[[ True False False]
 [False  True False]
 [False False  True]]


In [28]:
x = np.zeros(5)

In [29]:
print(x)

[0. 0. 0. 0. 0.]


In [30]:
x = np.zeros([2,3])

In [31]:
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [33]:
y = np.zeros_like(x)

In [34]:
print(y)

[[0 0 0]
 [0 0 0]]


In [36]:
x = np.ones(5)

In [37]:
print(x)

[1. 1. 1. 1. 1.]


In [38]:
x = np.ones([2, 3])

In [39]:
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [40]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [41]:
print(x)

[[1 2 3]
 [4 5 6]]


In [42]:
y = np.ones_like(x)

In [43]:
y

array([[1, 1, 1],
       [1, 1, 1]])

In [44]:
x = np.empty(5)

In [45]:
x

array([1., 1., 1., 1., 1.])

In [46]:
print(x)

[1. 1. 1. 1. 1.]


In [47]:
a = np.empty(5)

In [48]:
a

array([1., 1., 1., 1., 1.])

In [49]:
x = np.empty((3,2))

In [50]:
print()

In [51]:
print(x)

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323]]


In [55]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.empty_like(x)

In [53]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
print(x)

[[1 2 3]
 [4 5 6]]


In [57]:
q = np.empty(5)

In [58]:
q

array([1., 1., 1., 1., 1.])

In [59]:
np.empty([2,3])

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [62]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [64]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [65]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [66]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [67]:
x = np.arange(9).reshape(3,3)

In [69]:
print(3)

3


In [70]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [72]:
print(np.diag(x))

[0 4 8]


In [73]:
print(np.diag(x, k=1))

[1 5]


In [74]:
print(np.diag(x, k=-1))

[3 7]


In [75]:
v = [1, 3, 5, 7]

In [76]:
x = np.diag(v)

In [77]:
print(x)

[[1 0 0 0]
 [0 3 0 0]
 [0 0 5 0]
 [0 0 0 7]]


In [82]:
x = np.full((2,), 7)

In [83]:
print(x)

[7 7]


In [84]:
x = np.full(2, 7)

In [85]:
print(x)

[7 7]


In [86]:
x = np.array([[1, 2, 3], [4, 5, 6]])


In [87]:
y = np.full_like(x, 7)

In [88]:
print(y)

[[7 7 7]
 [7 7 7]]


In [89]:
x = np.arange(5)

In [90]:
print(x)

[0 1 2 3 4]


In [91]:
x = np.arange(3, 7 ,2)

In [92]:
print(x)

[3 5]


In [93]:
x = np.linspace(start=0, stop=2, num=9)

In [94]:
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

##### x = np.logspace(0, 1,)

In [95]:
x = np.logspace(0, 1, 5)

In [96]:
x

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [100]:
print(np.around(x,1))

[ 1.   1.8  3.2  5.6 10. ]


In [101]:
x = np.linspace(start=0, stop=1, num=5)

In [102]:
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [103]:
x = [10 ** i for i in x]

In [104]:
x

[1.0, 1.7782794100389228, 3.1622776601683795, 5.623413251903491, 10.0]

In [105]:
print(np.around(x, 2))

[ 1.    1.78  3.16  5.62 10.  ]


In [106]:
x = np.random.random([2, 3])

In [107]:
x

array([[0.00951578, 0.62348686, 0.58491786],
       [0.22388051, 0.75937198, 0.33118392]])

In [110]:
x = np.random.rand(2, 3)

In [111]:
x

array([[0.60601352, 0.59681175, 0.43146456],
       [0.93686705, 0.26638547, 0.81661635]])

In [112]:
personType = np.dtype({
    'names' : ['name', 'age', 'weight'],
    'formats' : ['U30', 'i8', 'f8']
})

In [113]:
a = np.array([('liming', 24, 63.9), ('Mike', 15, 67.), ('Jan', 34, 45.8)], dtype=personType)


In [114]:
print(a, type(a))

[('liming', 24, 63.9) ('Mike', 15, 67. ) ('Jan', 34, 45.8)] <class 'numpy.ndarray'>


In [115]:
a[0]

('liming', 24, 63.9)

In [116]:
a[1]

('Mike', 15, 67.)

In [117]:
a[2]

('Jan', 34, 45.8)

In [119]:
personType = np.dtype([('name', 'U30'), ('age', 'i8'), ('weight', 'f8')])

In [120]:
a = np.array([('liming', 24, 63.9), ('mike', 15, 67.), ('Jan', 34, 45.8)], dtype=personType)

In [121]:
print(a, type(a))

[('liming', 24, 63.9) ('mike', 15, 67. ) ('Jan', 34, 45.8)] <class 'numpy.ndarray'>


In [122]:
a[0]

('liming', 24, 63.9)

In [123]:
a[1]

('mike', 15, 67.)

In [124]:
a[2]

('Jan', 34, 45.8)

In [125]:
print(a[-2:])

[('mike', 15, 67. ) ('Jan', 34, 45.8)]


In [126]:
print(a['name'])

['liming' 'mike' 'Jan']


In [127]:
print(a['age'])

[24 15 34]


In [129]:
print(a['weight'])

[63.9 67.  45.8]
