In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
y = x + 1

In [4]:
print(y)

[2 3 4 5 6 7 8 9]


# print(np.add(x, ))

In [5]:
print(np.add(x, 1))

[2 3 4 5 6 7 8 9]


In [6]:
print(np.add(x, 2))

[ 3  4  5  6  7  8  9 10]


In [7]:
print(x)

[1 2 3 4 5 6 7 8]


In [8]:
print(np.multiply(x, 2))

[ 2  4  6  8 10 12 14 16]


In [9]:
print(np.divide(x, 2))

[0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [10]:
print(np.floor_divide(x, 2))

[0 1 1 2 2 3 3 4]


In [11]:
y = x ** 2

In [12]:
print(y)

[ 1  4  9 16 25 36 49 64]


In [13]:
x = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30], [31, 32, 33, 34, 35]])

In [14]:
print(x)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [15]:
y = np.arange(1, 6)

In [16]:
print(y)

[1 2 3 4 5]


In [17]:
z = x + y

In [18]:
print(z)

[[12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]
 [27 29 31 33 35]
 [32 34 36 38 40]]


In [19]:
z = x - x

In [20]:
z = x - y

In [21]:
print(z)

[[10 10 10 10 10]
 [15 15 15 15 15]
 [20 20 20 20 20]
 [25 25 25 25 25]
 [30 30 30 30 30]]


In [22]:
print(np.subtract(x, y))

[[10 10 10 10 10]
 [15 15 15 15 15]
 [20 20 20 20 20]
 [25 25 25 25 25]
 [30 30 30 30 30]]


In [23]:
print(np.multiply(x, y))

[[ 11  24  39  56  75]
 [ 16  34  54  76 100]
 [ 21  44  69  96 125]
 [ 26  54  84 116 150]
 [ 31  64  99 136 175]]


In [24]:
print(np.divide(x, y))

[[11.          6.          4.33333333  3.5         3.        ]
 [16.          8.5         6.          4.75        4.        ]
 [21.         11.          7.66666667  6.          5.        ]
 [26.         13.5         9.33333333  7.25        6.        ]
 [31.         16.         11.          8.5         7.        ]]


In [25]:
print(np.floor_divide(x, y))

[[11  6  4  3  3]
 [16  8  6  4  4]
 [21 11  7  6  5]
 [26 13  9  7  6]
 [31 16 11  8  7]]


# np.full([])

In [27]:
a = np.full([1,5], 2)

In [28]:
y = np.arange(1, 26).reshape([5, 5])

In [29]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [30]:
z = x = y

In [31]:
z = x + y

In [32]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [33]:
print(z)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]


In [35]:
print(np.subtract(x, y))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [36]:
x = np.arange(1, 5)

In [37]:
print(x)

[1 2 3 4]


In [38]:
y = np.sqrt(x)

In [39]:
print(y)

[1.         1.41421356 1.73205081 2.        ]


In [40]:
print(np.power(x, 0.5))

[1.         1.41421356 1.73205081 2.        ]


In [42]:
x = np.linspace(start=0, stop=np.pi/2, num=10)

In [43]:
print(x)

[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]


In [44]:
y = np.sin(x)

In [45]:
print(y)

[0.         0.17364818 0.34202014 0.5        0.64278761 0.76604444
 0.8660254  0.93969262 0.98480775 1.        ]


In [46]:
print(np.arcsin(y))

[0.         0.17453293 0.34906585 0.52359878 0.6981317  0.87266463
 1.04719755 1.22173048 1.3962634  1.57079633]


In [47]:
print(np.cos(x))

[1.00000000e+00 9.84807753e-01 9.39692621e-01 8.66025404e-01
 7.66044443e-01 6.42787610e-01 5.00000000e-01 3.42020143e-01
 1.73648178e-01 6.12323400e-17]


In [48]:
print(np.cos(y))

[1.         0.984961   0.94207905 0.87758256 0.8004279  0.72065865
 0.64785934 0.59003622 0.5530233  0.54030231]


In [49]:
print(np.tan(y))

[0.         0.17541487 0.35601143 0.54630249 0.74888575 0.96202282
 1.17581075 1.3683512  1.50656544 1.55740772]


In [50]:
x = np.arange(1, 5)

In [51]:
print(x)

[1 2 3 4]


In [52]:
y = np.exp(x)

In [53]:
print(y)

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [54]:
z = np.log(y)

In [55]:
print(z)

[1. 2. 3. 4.]


In [56]:
x = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30], [31, 32, 33, 34, 35]])

In [57]:
y = np.sum(x)

In [58]:
print(y)

575


In [59]:
y = np.sum(x, axis=0)

In [60]:
print(y)

[105 110 115 120 125]


In [61]:
y = np.sum(x, axis=1)

In [62]:
print(y)

[ 65  90 115 140 165]


In [64]:
y = np.cumsum(x, axis=1)

In [65]:
print(x)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [67]:
print(y)

[[ 11  23  36  50  65]
 [ 16  33  51  70  90]
 [ 21  43  66  90 115]
 [ 26  53  81 110 140]
 [ 31  63  96 130 165]]


In [68]:
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [69]:
print(np.prod(x))

3712525927079477248


In [70]:
print(np.prod(x, axis=1))

[  360360  1860480  6375600 17100720 38955840]
